### PR TITLE
[Makefile] prevent go-bindata from choosing wrong package

### PR DESCRIPTION
**Pull request by kescherCode**
It likes to choose "magneticow" instead of "main", which prevents the `go install` command that follows it from working.

Signed-off-by: Jeremy Kescher <jeremy@kescher.at>

### CODE REVIEW

**Comment by boramalper** [comment]
Thanks for the PR! I haven't encountered any error so I am not sure what this is fixing exactly. Would you mind sharing the issue you had?

**Comment by kescherCode** [comment]
As soon as I'm home, I can demonstrate copy exact error messages.

**Comment by kescherCode** [comment]
```
✔ /tmp/magnetico [master|✔] 
18:24 $ make magneticow
# TODO: minify files!
# https://github.com/kevinburke/go-bindata
go-bindata -o="cmd/magneticow/bindata.go" -prefix="cmd/magneticow/data/" cmd/magneticow/data/...
go install --tags fts5 "-ldflags=-s -w -X main.compiledOn=`date -u +%Y-%m-%dT%H:%M:%SZ`" ./cmd/magneticow
can't load package: package github.com/boramalper/magnetico/cmd/magneticow: found packages main (api.go) and magneticow (bindata.go) in /tmp/magnetico/cmd/magneticow
make: *** [Makefile:12: magneticow] Error 1
```

**Comment by boramalper** [comment]
Just merged as I think both behaviours are correct (on my machine) and it seems that it fixes yours too so why not? :) Apologies for the long delay, and thanks for your contribution!

**Pull request closed without merging**
