### PR TITLE
Add Bloom filter to info_hash

### PR DESCRIPTION
**Pull request by ad-m**
Hello,

I am would like suggest add bloom filter to make memory usage predictable and constant (great idea, @boramalper ). This branch depends on #58, so them review first, please. 

Greetings,

### CODE REVIEW

**Comment by ad-m** [comment]
dane
[mprofile_20170430093002.dat.txt](https://github.com/boramalper/magnetico/files/967068/mprofile_20170430093002.dat.txt)

**Comment by richardkiss** [comment]
This is a clever idea, but I think a bloom filter has the wrong semantics – it gives false positives rather than false negatives. That means if the bloom filter says it's seen the infohash, you have to ask the DB anyway.

So I'd say we remove the RAM cache of the DB, and just ask the DB each time. Even if the DB ends up takes five seconds to return (which I doubt), it can be done asynchronously. Whether we start fetching the infohash data now or five seconds from now doesn't make much difference.

If this ends up being too slow because of disk accesses, we can add a caching layer later. But my instinct says it won't be necessary.

**Comment by ad-m** [comment]
In TODO list there is @boramalper  concept:
> Replace the Bloom Filter in magneticod with the opposite of a bloom filter. The latter "may claim that it has not seen an item when it has, but will never claim to have seen an item it has not."
> Better because we'll never miss any torrents!

**Comment by itdaniher** [comment]
I use redis as a LRU cache. It works quite well, but requires RAM. It will never report a false positive. Sqlite might be fast enough to work, but ideally we would want to keep track of all infohashes we've seen, not just the ones with bittorrent info attached.

https://github.com/itdaniher/mana/blob/master/mana.py#L34

**Comment by boramalper** [comment]
Closing the PR as we are querying the database directly instead.

**Comment by ad-m** [comment]
@boramalper what alternatives to optimize memory usage?

**Comment by boramalper** [comment]
> what alternatives to optimize memory usage?

I didn't get what you mean?

**Comment by ad-m** [comment]
No matter, I miss 0e389aa619fed41c93dd7b6ef2eaf24fcbe25fa0 .

**Pull request closed without merging**
