### PR TITLE
Windows Execution Fix / SQLITE3 first run index creation problem Fix

### PR DESCRIPTION
**Pull request by donaldsteele**
Fixed issue with windows compile where the sqlite3 urn was not properly  …
being generated

Fixed error with first run where it would crash while trying to drop  …
nonexistant index info_hash_index

### CODE REVIEW

**Comment by boramalper** [comment]
Hey @donaldsteele! I made some changes to bring `Database` interface in align with the [**magneticow** API](https://app.swaggerhub.com/apis/boramalper/magneticow-api/v0) (which is also discussed in #162).

I'd like to hear your feedback about the changes, and it would be great if you can also modify your PR accordingly.

Many thanks!

**Comment by donaldsteele** [comment]
I like the direction with the api changes . If you would please reject this pull request so I can rebase on my side and start making the modifications it would be appreciated . 

The api changes look good , one thing I think would be good would be to add a category of the torrents or files (I have some preliminary code currently ) . If that is something you think you would like to integrate .

**Comment by donaldsteele** [comment]
reworking based on changes to base.

**Comment by boramalper** [comment]
@donaldsteele And how do we categorise torrents exactly? I thought about it as well, and my plan was to make changes to the web interface only, so that when you search the category "movies" for instance, it will append certain keywords at the end of your query (such as "hd", "webrip", etc).

**Comment by donaldsteele** [comment]
so the first iteration i have been playing with is by file extension . so if the torrent contains mostly .mp4 files it is a movie, .wav it is audio, .epub it is a book etc, .iso presents a challenge because it could be an app or a game rip but that can be its own category i suppose. Then once you have the high level classification keywords like h264 or complete can be used to further refine the categories into subcategories. I have been looking over the logic in the filebot project for inspiration on how to identify movies and tv series specifically.

**Comment by skobkin** [comment]
> if the torrent contains mostly .mp4 files it is a movie, .wav it is audio, .epub it is a book etc

It can work but for part of the torrents only. Many movie torrents contains 2-3 `*.nfo` / `*.lnk` / `*.txt` files besides of movie file. Also there can be torrents with one MP4 file (movie) and 1-5 alternative audio tracks with it in separate files.

**Comment by boramalper** [comment]
I think checking the name is a better idea, as its simpler and more reliable. We can search for some formats such as `S\d+E\d+`, [warez group name](https://en.wikipedia.org/wiki/List_of_warez_groups) (*SKIDROW*, *Razor 1911* etc. for games, *aXXo*, *YIFY* for movies, and so on), keywords (*e.g.* "HD", "Season", "lossless" etc.), and so on and so forth.

What do you think?

**Comment by donaldsteele** [comment]
true, separation of duties is a good thing. I assumed the direction was to go towards internal classification due to the addition of the readme column in the schema.

**Comment by skobkin** [comment]
Pardon me for putting my two cents again.

At first why do we at all need any categorization logic in `magneticod`?

> warez group name

Then they will be hardcoded? It's good for centralized service with content moderators when if something changes updates can follow immediately but for me it seems not very reliable for Magnetico.

> keywords (e.g. "HD", "Season", "lossless" etc.)

For TV shows episodes we also can use the "S\d\dE\d\d" format.

> The idea is that, magneticow's web interface (and other clients) can add these to their queries automatically, so that we don't have to change our database schema, and maintain a list of filters & keywords.

It sounds more appropriate. What about performance with more complex queries like you suggest? Couldn't this be a problem with large data sets?

**Pull request closed without merging**
