### PR TITLE
Dockerize magnetico as a pair of conjoined containers

### PR DESCRIPTION
**Pull request by offbyone**
docker-compose links them, they share a DB on a volume container, and
expose the web interface on the host port 12345

### CODE REVIEW

**Comment by colinodell** [comment]
:+1: This approach works for me too.  Perhaps the commented-out instructions could be cleaned out as well?

**Comment by offbyone** [comment]
Good call. Fixed.

**Comment by boramalper** [comment]
Thank you so much for your contribution! Can you please update it for v0.2.0 so that I can merge it right away? Thanks!

**Comment by offbyone** [comment]
Updated

**Comment by ngosang** [comment]
> CMD ["python", "-mmagneticod", "--node-addr", "0.0.0.0:12345"]

CMD ["python", "-mmagneticod", "--node-addr", "0.0.0.0:8080"]

**Comment by ngosang** [comment]
> CMD ["python", "-mmagneticod", "--node-addr", "0.0.0.0:12345"]

No need, we only need to know the web interface.

**Comment by boramalper** [comment]
@ngosang I merge it then. Thanks!

**Pull request merged**
