### PR TITLE
Map concurrency fix, throttling, multi transport

### PR DESCRIPTION
**Pull request by lruggieri**
Fixed an initial issue with a missing lock.

Added the possibility to use multiple transports for the protocol. I implemented this because I thought that using a single socket with an average of 20k tps was causing all those EPERM errors, but apparently it was not the issue (nor was any iptables configuration, checked by allowing everything on it and I still got EPERMs).

Added a simple throttler to limit the tps. Nothing fancy, just a limiter on the number of requests (of any kind) send each second. It helped with the EPERMs problem. With 15k tps I get no more errors.

### CODE REVIEW

**Comment by skobkin** [comment]
It would probably be better to split your enhancements to separate PR's.

You could still have them all in any other git branch in your repo. But this way it will be simplier for @boramalper to review and merge changes which he want to merge.

I did same thing with my PR's. Each of my database engines are in separate branches. But I also have all of them merged in one more branch which I'm using to build `magneticod` with all engines included.

**Comment by lruggieri** [comment]
@skobkin 
agreed on the different commits. Working on it.

Regarding the EPERM problem: I already tried enabling the NOTRACK options, but I did not know which port to specify. That's why I tracked which ports where used most on the statistics I implemented.

Eg. {ports": "6881(36432), 51413(12408), 8999(4688), 50321(2019), 6882(1836), 6889(1289)", "send rate": "19014.4 msg/s", "read rate": "1514.5 msg/s"}

I used the first 4 most used ports on those rules, but I kept getting the problem. After this comment of yours I deep a little deeper and apparently you do not need to specify any port on those iptables configurations, meaning that

iptables -t raw -I PREROUTING -p udp -j NOTRACK
iptables -t raw -I OUTPUT -p udp -j NOTRACK

would work just fine. And indeed they are! I see no more EPERMS and I am still keeping a 20k tps on average.

**Comment by lruggieri** [comment]
Closing PR. Opening several PR to separate different enhancements.

**Comment by skobkin** [comment]
> but I did not know which port to specify

You just need to specify port which you've chosen when starting `magneticod` using [`--indexer-addr` ](https://github.com/boramalper/magnetico/blob/master/cmd/magneticod/main.go#L139) parameter.

> you do not need to specify any port on those iptables configurations
> `iptables -t raw -I PREROUTING -p udp -j NOTRACK`

Yes. But this way you're telling Netfilter not to track *ALL* UDP connections. It will work but it also could break something else using UDP.

**Pull request closed without merging**
