### PR TITLE
integrating circleci

### PR DESCRIPTION
**Pull request by lruggieri**
Enables circleci.

image

### CODE REVIEW

**Comment by ad-m** [comment]
Why CircleCI (nor GitHub Action, nor TravisCI, nor Azure Pipelines)?

**Comment by lruggieri** [comment]
@ad-m 
From what I see this project already has travis and appveyor.
Travis and CircleCI are [the 2 most used CI tools](https://www.cuelogic.com/blog/best-continuous-integration-ci-tools), but I could not say which one fits best on magnetico for the moment.
With this PR I just wanted to start making a comparison between the 2, but maybe it's only creating more confusion?
Did not try GitHub one yet.

**Comment by ad-m** [comment]
If the project has TravisCI and AppVeyor currently integrated, why should one more be integrated? What are the benefits and advantages of this?

**Comment by lruggieri** [comment]
Merging this PR would likely have no benefit, if TravisCI is already the chosen one. But then why is there an appveyor.yml, which is not passing? I was thinking having these 3 together would be nice for making a comparison.

**Comment by ad-m** [comment]
I don't know AppVeyor, but it seems to me that it is a CI system that successfully tests on the Windows platform. TravisCI successfully performs tests on the Linux platform. In this case, both complement each other, not repeat.

I think that instead of introducing another CI system and counting on the fact that one system will work, it is necessary to fix the tests to give reproducible results (for developers before-push and in the CI system after-push).

**Comment by lruggieri** [comment]
Agreed. Did not think about the windows/linux difference. Closing this PR.

Regarding the travis file. I took a look and there are 2 problems: 

- `dep-windows-amd64` should be substituted with `dep-windows-amd64.exe` 
- git has not been installed, so `go get` fails

will look further into it.

**Pull request closed without merging**
