### PR TITLE
Fix dep URL on AppVeyor CI

### PR DESCRIPTION
**Pull request by ad-m**

### CODE REVIEW

**Comment by lruggieri** [comment]
We should move from dep to modules

**Comment by ad-m** [comment]
I don't know Go enough to switch from dep to modules whole project.

**Comment by ad-m** [comment]
I don't have idea about minigw issue :-/

**Comment by lruggieri** [comment]
> I don't have idea about minigw issue :-/

go-sqlite3 is using gco, which enables calling C libraries in go packages. There is likely some gcc problem in mingw.
I tried with cygwin also but there are even more issues...

Is it worth having a windows CI? Users who wants to run magnetico on Windows can always use the Docker version

**Comment by boramalper** [comment]
@ad-m What is the latest status? Does AppVeyor work again with this PR?

**Comment by boramalper** [comment]
I am closing this since we have switched to modules instead. I'll try to fix appveyor myself.

**Pull request closed without merging**
