### PR TITLE
Docker

### PR DESCRIPTION
**Pull request by colinodell**
This is an early attempt to get magnetico working in Docker (see #4)

If you have Docker installed, you can build and run the image with these commands:

```
docker build -t magnetico .
docker run -it --rm magnetico
```

Known issues which need to be resolved:

 - [ ] `magneticod` spews out several `Belated TICK` warnings (possibly related to #1? If we don't know the UDP port, we can't tell Docker to expose it to the host)
 - [ ] No search results appear (probably due to the above issue)
 - [ ] The web credentials are currently hard-coded to `user` / `password`. Would be nice if we could set those via environment variables instead

### CODE REVIEW

**Comment by offbyone** [comment]
Consider #13 instead, which builds this as a pair of separate containers; that might be more flexible in the long run.

**Comment by boramalper** [comment]
I agree with @offbyone that a pair of separate containers might be a better choice.

@colinodell I will do the required changes but I didn't understand this:
>The web credentials are currently hard-coded to user / password. Would be nice if we could set those via environment variables instead

The credentials can be set from the command-line while starting the program. Isn't it a better option than using environment variables which can lead to a mess quite easily?

**Comment by r4j4h** [comment]
Regarding `magneticod spews out several Belated TICK warnings (possibly related to #1? If we don't know the UDP port, we can't tell Docker to expose it to the host)` Docker lets us specify port ranges.

```
EXPOSE 7000-8000
```

[Expose reference](https://docs.docker.com/engine/reference/builder/#expose)
[SO Syntax reference](http://stackoverflow.com/a/28721643/1347604) and [SO Syntax w/ specific interface example](http://stackoverflow.com/a/30347575/1347604)

Hope that is helpful news :)

**Comment by colinodell** [comment]
> Consider #13 instead, which builds this as a pair of separate containers; that might be more flexible in the long run.

I usually do prefer separate containers for separate services.  In this case I wonder how useful it is to have one container without the other, especially since they communicate via a shared database and not the network.

If you'd still prefer the two-image approach then feel free to close this :)

> The credentials can be set from the command-line while starting the program. Isn't it a better option than using environment variables which can lead to a mess quite easily?

I've personally never encountered a mess using environment variables with Docker in this way.  I know it's dead-simple to pass them into a command - I just didn't spend the time figuring out if that was doable with supervisord (which would not be needed if we went with #13)

> Regarding magneticod spews out several Belated TICK warnings (possibly related to #1? If we don't know the UDP port, we can't tell Docker to expose it to the host) Docker lets us specify port ranges.

That does help somewhat, but it's still not ideal.  Yes, we could define the entire range the application might use, but ultimately it's always going to use a single port, so I'd rather have the ability to configure which port I'm going to use (instead of tying up 1000 ports on the host because I have no way to pre-determine which port will be used).

**Comment by offbyone** [comment]
FWIW the reason I looked at separate containers was because of the different resource needs; the `magneticod` container has different memory and CPU requirements, so it should be in a different container. Sharing data via the volume is pretty much why that feature exists.

**Pull request closed without merging**
